// =========================================================================
// Project ErrCo: ErrCo StarCore-1 Co-Proccessor Control Module
// =========================================================================
//
// Project Group 10
//
// MEMBERS:
//   - Member 1 Zameer Mahomed, MHMZAM005
//   - Member 2 Mahir Khan, KHNMAH014

// File        : ErrCo_Control.v
// Description : SEC-DED Hamming(22,16) Control Module to route data and call Encoder, Decoder and Parity modules
//
//   iverilog -Wall -I ../src -o ../build/ErrCo_Control_sim ../src/ErrCo_Control.v ErrCo_Control_tb.v - need to be in tb
//   cd ../test && ../build/ErrCo_Control_sim -- need to be in test
//   gtkwave ../waves/ErrCo_Control_tb.vcd &
//  cd .. && cd tb && iverilog -Wall -I ../src -o ../build/ErrCo_Control_sim ../src/ErrCo_Control.v ErrCo_Control_tb.v && cd ../test && ../build/ErrCo_Control_sim
// =============================================================================

`timescale 1ns / 1ps

module ErrCo_Control(
    input clk,

    input   parity_write_en, //enable parity storage
    input [15:0] mem_access_addr,

    input [15:0] data_encoder, //data to Encoder
    input [15:0] data_to_decoder, //data to decoder to check and correct

    output [15:0] Error_Corr_Result,
    output SE_flag, // there is a single error that was fixed (we dont actaully need this but useful for debugging)
    output DE_flag, // there is a double error that can't be fixed
    output parity_bit_error // ADDED: SE was in a stored parity bit (data clean) - threaded up from Decoder for SCRUB
);

// =========================================================================
// INTERNAL SIGNAL DECLARATIONS
// All internal signals that interconnect sub-components go here.
// =========================================================================
wire [5:0] parity_encoded; // Parity Generated by encoder
wire [5:0] parity_retreived; //parity to retrieve from paroty_store

// =========================================================================
// Module Instantiation
// =========================================================================


Encoder ENC (
    .data_in(data_encoder),
    .parity(parity_encoded) //output generated parity
);

ParityStore PS (
    .clk(clk),
    .parity_write_en(parity_write_en),
    .mem_access_addr(mem_access_addr),
    .parity_in(parity_encoded),
    .parity_out(parity_retreived)
);

Decoder DEC (
    .data_in(data_to_decoder),
    .parity(parity_retreived),
    .Error_Corr_Result(Error_Corr_Result),
    .SE_flag(SE_flag),
    .DE_flag(DE_flag),
    .parity_bit_error(parity_bit_error) // ADDED
);

endmodule
